name: Testing SFSORT

on: [push]

jobs:
  test_python_module:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip install ultralytics
      - name: Run Python module with hidden artifacts
        run: python ultralytics_sfsort.py
