name: Testing SFSORT

on: [push]

jobs:
  test_python_module:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip install -U ultralytics ffmpeg-python
      - name: Run Python module to test if tracker works correctly
        run: python3 ultralytics_sfsort.py
